[package]
name = "quokka-vote"
version = "1.0.0"
authors = []

[addresses]
contract = "0x992cdbd460ff82e246d0b547f7f2c58db5533b162b13dfe2263058a70c16844a"
contract_resource_account = "0x1fd985dff3af603d6363878b0258704b8b72a1ed2f9bdac888b0c8d8daf3e943"
test_coin = "0x16"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Chef]
local = "../quokka-chef"

[dev-dependencies]
