[package]
name = "veqka"
version = "1.0.0"
authors = []

[addresses]
veqka = "0x47afb2cba83b1e111800a68e59c910e80e84186f61dffe9584393abbf8fdc3de"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.qka]
local = "../qka"


[dev-dependencies]
